import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { ADMIN_EMAIL, admin, audit, db, ensureSchema, secret } from './db.js';
export const ADMIN_COOKIE='btf_admin_session', VISITOR_COOKIE='btf_visitor_session';
export const sha256=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const safe=(a,b)=>{try{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y);}catch{return false;}};
export function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))];}));}
export function setCookie(res,name,value,{maxAge=0,httpOnly=true}={}){const p=[`${name}=${encodeURIComponent(value)}`,'Path=/','SameSite=Lax'];if(httpOnly)p.push('HttpOnly');if(process.env.VERCEL_ENV)p.push('Secure');if(maxAge)p.push(`Max-Age=${maxAge}`);const current=res.getHeader('Set-Cookie');res.setHeader('Set-Cookie',Array.isArray(current)?current.concat(p.join('; ')):current?[current,p.join('; ')]:[p.join('; ')]);}
async function sign(payload){const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',await secret()).update(body).digest('base64url');return `${body}.${sig}`;}
async function verify(token){if(!token)return null;const [body,sig]=String(token).split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',await secret()).update(body).digest('base64url');if(!safe(sig,expected))return null;try{const p=JSON.parse(Buffer.from(body,'base64url').toString());return p.exp>Date.now()?p:null;}catch{return null;}}
export async function requireAdmin(req){const p=await verify(cookies(req)[ADMIN_COOKIE]);if(p?.type!=='admin'||p.email!==ADMIN_EMAIL)return null;const a=await admin();return a?.setup_completed&&Number(a.session_version)===Number(p.version)?a:null;}
export async function adminSession(res,version){const age=7*24*3600;setCookie(res,ADMIN_COOKIE,await sign({type:'admin',email:ADMIN_EMAIL,version:Number(version),exp:Date.now()+age*1000}),{maxAge:age});}
export async function visitorSession(res,hours=24){const age=Math.max(1,Math.min(720,Number(hours)||24))*3600;setCookie(res,VISITOR_COOKIE,await sign({type:'visitor',exp:Date.now()+age*1000}),{maxAge:age});}
export async function visitorAllowed(req){return (await verify(cookies(req)[VISITOR_COOKIE]))?.type==='visitor';}
export async function setupPassword(password){await ensureSchema();const hash=await bcrypt.hash(password,12);await db()`UPDATE btf_admins SET password_hash=${hash},setup_completed=true,session_version=session_version+1,failed_attempts=0,locked_until=null,updated_at=now() WHERE email=${ADMIN_EMAIL}`;await audit(ADMIN_EMAIL,'admin_setup',{});return admin();}
export async function checkPassword(password){const a=await admin();if(!a?.setup_completed||!a.password_hash)return {ok:false,admin:a};if(a.locked_until&&new Date(a.locked_until)>new Date())return {ok:false,locked:true,admin:a};const ok=await bcrypt.compare(password,a.password_hash);if(ok){await db()`UPDATE btf_admins SET failed_attempts=0,locked_until=null,updated_at=now() WHERE email=${ADMIN_EMAIL}`;return {ok:true,admin:await admin()};}const attempts=Number(a.failed_attempts||0)+1,locked=attempts>=7;await db()`UPDATE btf_admins SET failed_attempts=${locked?0:attempts},locked_until=${locked?new Date(Date.now()+15*60000).toISOString():null},updated_at=now() WHERE email=${ADMIN_EMAIL}`;return {ok:false,locked};}
export async function changePassword(current,next){const result=await checkPassword(current);if(!result.ok)return false;const hash=await bcrypt.hash(next,12);await db()`UPDATE btf_admins SET password_hash=${hash},session_version=session_version+1,updated_at=now() WHERE email=${ADMIN_EMAIL}`;await audit(ADMIN_EMAIL,'password_changed',{});return true;}
